services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/login-system/protocol/openid-connect/certs
    depends_on:
      - keycloak
    restart: on-failure
