# ============ Servidor ============
server.port=8081
#server.servlet.context-path=/api

# ============ H2 Database ============
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ============ JPA ============
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============ H2 Console ============
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ============ Logs ============
logging.level.com.javanauta.todo_app=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ============ Erros na resposta (facilita debug local) ============
server.error.include-message=always
server.error.include-binding-errors=always
