-- Seed user (email: admin@email.com / password: admin123)
INSERT INTO users (name, email, password)
VALUES ('Admin', 'admin@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy')
ON CONFLICT (email) DO NOTHING;

INSERT INTO todo (id, title, description, completed, created_at, due_date, user_id) VALUES
(nextval('todo_seq'), 'Study Spring Boot', 'Review beans and context concepts', false, NOW(), NOW() + INTERVAL '7 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create REST API', 'Implement endpoints following REST standard', true, NOW() - INTERVAL '10 days', NOW() - INTERVAL '3 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure Docker', 'Create Dockerfile and docker-compose for the project', true, NOW() - INTERVAL '15 days', NOW() - INTERVAL '8 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Write unit tests', 'Cover service and controller with JUnit and Mockito', false, NOW(), NOW() + INTERVAL '5 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Review documentation', 'Update README with usage instructions', false, NOW(), NOW() + INTERVAL '3 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement pagination', 'Add Pageable to listing endpoints', false, NOW(), NOW() + INTERVAL '10 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Add authentication', 'Integrate Spring Security with JWT', false, NOW(), NOW() + INTERVAL '14 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Refactor service layer', 'Extract duplicated logic into private methods', true, NOW() - INTERVAL '5 days', NOW() - INTERVAL '1 day', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure Flyway', 'Replace ddl-auto with versioned migrations', false, NOW(), NOW() + INTERVAL '7 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Deploy to production', 'Deploy to AWS with ECR and ECS', false, NOW(), NOW() + INTERVAL '30 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study Hibernate', 'Understand lazy loading and sessions', false, NOW(), NOW() + INTERVAL '6 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement cache', 'Use Redis to cache listings', false, NOW(), NOW() + INTERVAL '12 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create CI/CD pipeline', 'Configure GitHub Actions for build and deploy', false, NOW(), NOW() + INTERVAL '20 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Review API security', 'Check CORS, headers and validations', false, NOW(), NOW() + INTERVAL '8 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Optimize queries', 'Analyze execution plans in PostgreSQL', false, NOW(), NOW() + INTERVAL '15 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Document with Swagger', 'Configure SpringDoc OpenAPI', true, NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Learn Kotlin', 'Study syntax and Java interop', false, NOW(), NOW() + INTERVAL '30 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Fix filter bug', 'Correct status filter returning wrong results', true, NOW() - INTERVAL '2 days', NOW(), (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Add structured logs', 'Configure Logback with JSON for production', false, NOW(), NOW() + INTERVAL '10 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study Kubernetes', 'Create manifests for deployment and service', false, NOW(), NOW() + INTERVAL '45 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Do code review', 'Review pending PRs from the team', false, NOW(), NOW() + INTERVAL '1 day', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Update dependencies', 'Check outdated versions in pom.xml', false, NOW(), NOW() + INTERVAL '5 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create staging environment', 'Provision intermediate environment between dev and prod', false, NOW(), NOW() + INTERVAL '25 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement rate limiting', 'Protect endpoints against abuse', false, NOW(), NOW() + INTERVAL '18 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study messaging', 'Explore RabbitMQ and Kafka for events', false, NOW(), NOW() + INTERVAL '30 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure monitoring', 'Integrate Prometheus and Grafana', false, NOW(), NOW() + INTERVAL '20 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Write integration tests', 'Test complete flows with real database', false, NOW(), NOW() + INTERVAL '7 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement soft delete', 'Add deleted_at field instead of physical delete', false, NOW(), NOW() + INTERVAL '9 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create monthly report', 'Generate PDF with monthly tasks', false, NOW(), NOW() + INTERVAL '28 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Learn design patterns', 'Study Factory, Strategy and Observer', false, NOW(), NOW() + INTERVAL '21 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure database backup', 'Automate daily PostgreSQL dump', false, NOW(), NOW() + INTERVAL '5 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Review architecture', 'Discuss microservices migration with the team', false, NOW(), NOW() + INTERVAL '14 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement notifications', 'Send email when task is overdue', false, NOW(), NOW() + INTERVAL '16 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study reactive programming', 'Explore WebFlux and Project Reactor', false, NOW(), NOW() + INTERVAL '35 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create seed script', 'Populate database with sample data', true, NOW() - INTERVAL '1 day', NOW(), (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Review error handling', 'Ensure consistent responses for 4xx and 5xx errors', false, NOW(), NOW() + INTERVAL '4 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Learn HATEOAS', 'Add navigation links to API responses', false, NOW(), NOW() + INTERVAL '12 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure dev profile', 'Separate configurations by environment', true, NOW() - INTERVAL '7 days', NOW() - INTERVAL '4 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study DDD', 'Apply rich domain concepts to the project', false, NOW(), NOW() + INTERVAL '40 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Add custom validation', 'Create @FutureDueDate annotation', false, NOW(), NOW() + INTERVAL '8 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Refactor DTOs', 'Use Java 16+ records for DTOs', false, NOW(), NOW() + INTERVAL '6 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement text search', 'Add endpoint to search by title and description', false, NOW(), NOW() + INTERVAL '11 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study load testing', 'Use k6 or Gatling to simulate load', false, NOW(), NOW() + INTERVAL '22 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Configure alerts', 'Create Grafana alerts for critical errors', false, NOW(), NOW() + INTERVAL '17 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Learn GraalVM native', 'Compile app to native binary with Spring Native', false, NOW(), NOW() + INTERVAL '50 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'General refactoring', 'Remove dead code and improve naming', false, NOW(), NOW() + INTERVAL '3 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Study multi-tenancy', 'Explore data isolation per tenant', false, NOW(), NOW() + INTERVAL '35 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Create custom health check', 'Add /actuator/health endpoint with custom checks', false, NOW(), NOW() + INTERVAL '9 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Implement audit trail', 'Record who created and changed each task', false, NOW(), NOW() + INTERVAL '13 days', (SELECT id FROM users WHERE email = 'admin@email.com')),
(nextval('todo_seq'), 'Prepare presentation', 'Create slides about REST API best practices', false, NOW(), NOW() + INTERVAL '7 days', (SELECT id FROM users WHERE email = 'admin@email.com'));
