# Perfil mTLS — ative com SPRING_PROFILES_ACTIVE=mtls
# Gere os certificados primeiro: scripts/generate-certs.sh

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE:classpath:certs/payment-keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    trust-store: ${SSL_TRUST_STORE:classpath:certs/payment-truststore.p12}
    trust-store-password: ${SSL_TRUST_STORE_PASSWORD:changeit}
    trust-store-type: PKCS12
    client-auth: need
