INSERT INTO todo (id, titulo, descricao, concluido, data_criacao, data_limite) VALUES
(nextval('todo_seq'), 'Estudar Spring Boot', 'Revisar conceitos de beans e contexto', false, NOW(), NOW() + INTERVAL '7 days'),
(nextval('todo_seq'), 'Criar API REST', 'Implementar endpoints seguindo padrão REST', true, NOW() - INTERVAL '10 days', NOW() - INTERVAL '3 days'),
(nextval('todo_seq'), 'Configurar Docker', 'Criar Dockerfile e docker-compose para o projeto', true, NOW() - INTERVAL '15 days', NOW() - INTERVAL '8 days'),
(nextval('todo_seq'), 'Escrever testes unitários', 'Cobrir service e controller com JUnit e Mockito', false, NOW(), NOW() + INTERVAL '5 days'),
(nextval('todo_seq'), 'Revisar documentação', 'Atualizar README com instruções de uso', false, NOW(), NOW() + INTERVAL '3 days'),
(nextval('todo_seq'), 'Implementar paginação', 'Adicionar Pageable nos endpoints de listagem', false, NOW(), NOW() + INTERVAL '10 days'),
(nextval('todo_seq'), 'Adicionar autenticação', 'Integrar Spring Security com JWT', false, NOW(), NOW() + INTERVAL '14 days'),
(nextval('todo_seq'), 'Refatorar service layer', 'Extrair lógica duplicada para métodos privados', true, NOW() - INTERVAL '5 days', NOW() - INTERVAL '1 day'),
(nextval('todo_seq'), 'Configurar Flyway', 'Substituir ddl-auto por migrations versionadas', false, NOW(), NOW() + INTERVAL '7 days'),
(nextval('todo_seq'), 'Subir para produção', 'Deploy na AWS com ECR e ECS', false, NOW(), NOW() + INTERVAL '30 days'),
(nextval('todo_seq'), 'Estudar Hibernate', 'Entender lazy loading e sessões', false, NOW(), NOW() + INTERVAL '6 days'),
(nextval('todo_seq'), 'Implementar cache', 'Usar Redis para cachear listagens', false, NOW(), NOW() + INTERVAL '12 days'),
(nextval('todo_seq'), 'Criar CI/CD pipeline', 'Configurar GitHub Actions para build e deploy', false, NOW(), NOW() + INTERVAL '20 days'),
(nextval('todo_seq'), 'Revisar segurança da API', 'Verificar CORS, headers e validações', false, NOW(), NOW() + INTERVAL '8 days'),
(nextval('todo_seq'), 'Otimizar queries', 'Analisar planos de execução no PostgreSQL', false, NOW(), NOW() + INTERVAL '15 days'),
(nextval('todo_seq'), 'Documentar com Swagger', 'Configurar SpringDoc OpenAPI', true, NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day'),
(nextval('todo_seq'), 'Aprender Kotlin', 'Estudar sintaxe e interop com Java', false, NOW(), NOW() + INTERVAL '30 days'),
(nextval('todo_seq'), 'Resolver bug no filtro', 'Corrigir filtro por status retornando resultado errado', true, NOW() - INTERVAL '2 days', NOW()),
(nextval('todo_seq'), 'Adicionar logs estruturados', 'Configurar Logback com JSON para produção', false, NOW(), NOW() + INTERVAL '10 days'),
(nextval('todo_seq'), 'Estudar Kubernetes', 'Criar manifests para deployment e service', false, NOW(), NOW() + INTERVAL '45 days'),
(nextval('todo_seq'), 'Fazer code review', 'Revisar PRs pendentes do time', false, NOW(), NOW() + INTERVAL '1 day'),
(nextval('todo_seq'), 'Atualizar dependências', 'Verificar versões desatualizadas no pom.xml', false, NOW(), NOW() + INTERVAL '5 days'),
(nextval('todo_seq'), 'Criar ambiente de staging', 'Provisionar ambiente intermediário entre dev e prod', false, NOW(), NOW() + INTERVAL '25 days'),
(nextval('todo_seq'), 'Implementar rate limiting', 'Proteger endpoints contra abuso', false, NOW(), NOW() + INTERVAL '18 days'),
(nextval('todo_seq'), 'Estudar mensageria', 'Explorar RabbitMQ e Kafka para eventos', false, NOW(), NOW() + INTERVAL '30 days'),
(nextval('todo_seq'), 'Configurar monitoramento', 'Integrar Prometheus e Grafana', false, NOW(), NOW() + INTERVAL '20 days'),
(nextval('todo_seq'), 'Escrever testes de integração', 'Testar fluxos completos com banco real', false, NOW(), NOW() + INTERVAL '7 days'),
(nextval('todo_seq'), 'Implementar soft delete', 'Adicionar campo deleted_at ao invés de deletar físico', false, NOW(), NOW() + INTERVAL '9 days'),
(nextval('todo_seq'), 'Criar relatório mensal', 'Gerar PDF com tarefas do mês', false, NOW(), NOW() + INTERVAL '28 days'),
(nextval('todo_seq'), 'Aprender design patterns', 'Estudar Factory, Strategy e Observer', false, NOW(), NOW() + INTERVAL '21 days'),
(nextval('todo_seq'), 'Configurar backup do banco', 'Automatizar dump diário do PostgreSQL', false, NOW(), NOW() + INTERVAL '5 days'),
(nextval('todo_seq'), 'Revisar arquitetura', 'Discutir com o time a migração para microsserviços', false, NOW(), NOW() + INTERVAL '14 days'),
(nextval('todo_seq'), 'Implementar notificações', 'Enviar email quando tarefa vencer', false, NOW(), NOW() + INTERVAL '16 days'),
(nextval('todo_seq'), 'Estudar reactive programming', 'Explorar WebFlux e Project Reactor', false, NOW(), NOW() + INTERVAL '35 days'),
(nextval('todo_seq'), 'Criar script de seed', 'Popular banco com dados de exemplo', true, NOW() - INTERVAL '1 day', NOW()),
(nextval('todo_seq'), 'Revisar tratamento de erros', 'Garantir respostas consistentes em erros 4xx e 5xx', false, NOW(), NOW() + INTERVAL '4 days'),
(nextval('todo_seq'), 'Aprender HATEOAS', 'Adicionar links de navegação nas respostas da API', false, NOW(), NOW() + INTERVAL '12 days'),
(nextval('todo_seq'), 'Configurar profile de dev', 'Separar configurações por ambiente', true, NOW() - INTERVAL '7 days', NOW() - INTERVAL '4 days'),
(nextval('todo_seq'), 'Estudar DDD', 'Aplicar conceitos de domínio rico no projeto', false, NOW(), NOW() + INTERVAL '40 days'),
(nextval('todo_seq'), 'Adicionar validação customizada', 'Criar anotação @DataLimiteFutura', false, NOW(), NOW() + INTERVAL '8 days'),
(nextval('todo_seq'), 'Refatorar DTOs', 'Usar records do Java 16+ nos DTOs', false, NOW(), NOW() + INTERVAL '6 days'),
(nextval('todo_seq'), 'Implementar busca por texto', 'Adicionar endpoint de busca por título e descrição', false, NOW(), NOW() + INTERVAL '11 days'),
(nextval('todo_seq'), 'Estudar testes de carga', 'Usar k6 ou Gatling para simular carga', false, NOW(), NOW() + INTERVAL '22 days'),
(nextval('todo_seq'), 'Configurar alertas', 'Criar alertas no Grafana para erros críticos', false, NOW(), NOW() + INTERVAL '17 days'),
(nextval('todo_seq'), 'Aprender GraalVM native', 'Compilar app para binário nativo com Spring Native', false, NOW(), NOW() + INTERVAL '50 days'),
(nextval('todo_seq'), 'Fazer refactoring geral', 'Remover código morto e melhorar nomes', false, NOW(), NOW() + INTERVAL '3 days'),
(nextval('todo_seq'), 'Estudar multi-tenancy', 'Explorar isolamento de dados por tenant', false, NOW(), NOW() + INTERVAL '35 days'),
(nextval('todo_seq'), 'Criar health check customizado', 'Adicionar endpoint /actuator/health com verificações', false, NOW(), NOW() + INTERVAL '9 days'),
(nextval('todo_seq'), 'Implementar audit trail', 'Registrar quem criou e alterou cada tarefa', false, NOW(), NOW() + INTERVAL '13 days'),
(nextval('todo_seq'), 'Preparar apresentação', 'Montar slides sobre boas práticas de API REST', false, NOW(), NOW() + INTERVAL '7 days');
