spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:webhook_user}
    password: ${SPRING_DATASOURCE_PASSWORD:webhook_pass}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

order-service:
  url: ${ORDER_SERVICE_URL:http://localhost:8081}

webhook:
  secret: ${WEBHOOK_SECRET:dev-secret-change-me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
