spring.application.name=keycloak-login-sistem
server.port=8081

keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080}
keycloak.realm=login-system
keycloak.client-id=login-client
keycloak.admin-username=admin
keycloak.admin-password=admin

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/login-system/protocol/openid-connect/certs}
