spring.application.name=email-service
server.port=8081

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Mailtrap SMTP
# Crie sua conta em https://mailtrap.io e cole as credenciais abaixo
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME:94a4464c859e50}
spring.mail.password=${MAILTRAP_PASSWORD:43b0495b90aa4c}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from=noreply@userservice.com
