services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookstore-jpa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore-jpa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: banco123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
